site_name: CLIMB | Cloud Infrastructure for Microbial Bioinformatics
site_url: https://telatin.github.io/mm-docs/

theme:
  name: null
  custom_dir: theme/
  logo: assets/logo-square_CLIMB-BIG-DATA.png
  favicon: assets/logo-square_CLIMB-BIG-DATA.png
  language: en

plugins:
  - search

markdown_extensions:
  - attr_list
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption

copyright: "Copyright &copy; CLIMB 2026"

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:climb@quadram.ac.uk
